import {IProject} from './IProject';

export const mockProjects: IProject[] = [
    {
        title: 'Zebra Aurora',
        description: 'Machine Vision and Fixed Scanning Solution',
        definition: 'A desktop application used to provision and deploy machine vision jobs to a connected camera.',
        responsibility: 'I helped bring the product from R&D prototype, to full scale product. I owned and delivered major feature areas, most notably an undo/redo engine based on a reactive architecture.',
        technologiesUsed: 'Electron, React, TypeScript, Node.js, RXJS',
        featuredImageUri: 'aurora_featured.jpg',
        thumbnailImageUri: 'zebra_aurora.png',
        resourceUrl: 'https://www.youtube.com/watch?v=_6Eenn8dWDY',
    },
    {
        title: 'Age By Planet',
        description: 'Multi-Planetary Web App Utility',
        definition: 'A web app used to determine a user\'s age on different planets.',
        responsibility: 'I created this web app out of my daughter\'s love for planets. This app was bootstrapped from create-react-app and utilized GitHub actions for CI/CD.',
        technologiesUsed: 'React, TypeScript, Google Cloud, GitHub Actions',
        featuredImageUri: 'age_by_planet_featured.png',
        thumbnailImageUri: 'age_by_planet_thumb.png',
        resourceUrl: 'https://age-by-planet.web.app/',
        sourceControlUrl: 'https://github.com/mattrusso9037/age_by_planet',
    },
    {
        title: 'Simpli Budget',
        description: 'Multi-Planetary Web App Utility',
        definition: 'A web app used to determine a user\'s age on different planets.',
        responsibility: 'I created this web app out of my daughter\'s love for planets. This app was bootstrapped from create-react-app and utilized GitHub actions for CI/CD.',
        technologiesUsed: 'React, TypeScript, Google Cloud, GitHub Actions',
        featuredImageUri: 'age_by_planet_featured.png',
        thumbnailImageUri: 'age_by_planet_thumb.png',
        resourceUrl: 'https://age-by-planet.web.app/',
        sourceControlUrl: 'https://github.com/mattrusso9037/age_by_planet',
    },
    {
        title: 'Fitbit Watch Face',
        description: 'Multi-Planetary Web App Utility',
        definition: 'A web app used to determine a user\'s age on different planets.',
        responsibility: 'I created this web app out of my daughter\'s love for planets. This app was bootstrapped from create-react-app and utilized GitHub actions for CI/CD.',
        technologiesUsed: 'React, TypeScript, Google Cloud, GitHub Actions',
        featuredImageUri: 'age_by_planet_featured.png',
        thumbnailImageUri: 'age_by_planet_thumb.png',
        resourceUrl: 'https://age-by-planet.web.app/',
        sourceControlUrl: 'https://github.com/mattrusso9037/age_by_planet',
    },
    {
        title: 'Conquer Money',
        description: 'Multi-Planetary Web App Utility',
        definition: 'A web app used to determine a user\'s age on different planets.',
        responsibility: 'I created this web app out of my daughter\'s love for planets. This app was bootstrapped from create-react-app and utilized GitHub actions for CI/CD.',
        technologiesUsed: 'React, TypeScript, Google Cloud, GitHub Actions',
        featuredImageUri: 'age_by_planet_featured.png',
        thumbnailImageUri: 'age_by_planet_thumb.png',
        resourceUrl: 'https://age-by-planet.web.app/',
        sourceControlUrl: 'https://github.com/mattrusso9037/age_by_planet',
    },
];
